#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cat >&2 <<'EOF'
The old hand-authored XML pack workflow has been retired because Dataverse rejected
its table metadata with "PrimaryName attribute not found".

Use the Dataverse bootstrap/export workflow instead:

  ./scripts/first-install.sh --environment-url https://YOUR-DEV.crm3.dynamics.com

That command creates the schema through the supported Dataverse Web API and then
exports authoritative solution ZIPs generated by Dataverse.
EOF
exit 2
