#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PAC_BIN="${PAC_BIN:-pac}"

ENVIRONMENT_URL=""
EXPORT_MANAGED=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --environment-url) ENVIRONMENT_URL="${2:-}"; shift 2 ;;
    --managed) EXPORT_MANAGED=true; shift ;;
    -h|--help)
      cat <<'EOF'
Usage: ./scripts/export-solutions.sh --environment-url URL [--managed]
Exports Dataverse-generated schema and full solution packages.
EOF
      exit 0 ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

[[ -n "$ENVIRONMENT_URL" ]] || { echo "--environment-url is required" >&2; exit 2; }
command -v "$PAC_BIN" >/dev/null 2>&1 || { echo "Power Platform CLI (pac) was not found." >&2; exit 1; }

mkdir -p "$ROOT_DIR/solution/exported/schema" "$ROOT_DIR/solution/exported/full"

"$PAC_BIN" auth create --environment "$ENVIRONMENT_URL"

export_one() {
  local unique_name="$1"
  local base_path="$2"
  local version="$3"
  local unmanaged_path="${base_path}/${unique_name}_${version}_unmanaged.zip"
  echo "Exporting unmanaged solution: $unique_name"
  "$PAC_BIN" solution export --name "$unique_name" --path "$unmanaged_path" --overwrite
  echo "Created: $unmanaged_path"
  if [[ "$EXPORT_MANAGED" == true ]]; then
    local managed_path="${base_path}/${unique_name}_${version}_managed.zip"
    echo "Exporting managed solution: $unique_name"
    "$PAC_BIN" solution export --name "$unique_name" --path "$managed_path" --managed --overwrite
    echo "Created: $managed_path"
  fi
}

export_one "CloudstruccPagesSchema" "$ROOT_DIR/solution/exported/schema" "1_0_5_0"
export_one "CloudstruccPagesStudio" "$ROOT_DIR/solution/exported/full" "1_0_5_0"

echo "Solution export completed. These ZIPs were generated by Dataverse and are the packages to import elsewhere."
